spring:

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #??
    suffix: .html #????
    mode: HTML #??
  application.name:
    SingleUserMultiLoginRestriction
  data:
    redis:
      port: 6379
      host: 122.51.109.18
      password: hx801219

