spring:

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #??
    suffix: .html #????
    mode: HTML #??
  application.name:
    SingleUserMultiLoginRestriction
  data:
    redis:
      port: 6379
      host: localhost
      password: #????????????

